#!/usr/bin/env python3
#
##############################################################################
#
# MODULE:       model
#
# AUTHOR(S):    josephh
#
# PURPOSE:      Script generated by wxGUI Graphical Modeler.
#
# DATE:         Wed Mar 17 23:39:42 2021
#
##############################################################################

#%module
#% description: Script generated by wxGUI Graphical Modeler.
#%end
#%option
#% key: vbuffer3_where
#% description: WHERE conditions of SQL statement without 'where' keyword
#% required: yes
#% type: string
#% key_desc: sql_query
#%end

import sys
import os
import atexit

from grass.script import parser, run_command

def cleanup():
    pass

def main(options, flags):
    run_command("v.buffer",
                overwrite = True,
                input="CHaMP_Data_MFJD@PERMANENT",
                layer="-1",
                where=options["vbuffer3_where"],
                type="point,line,area",
                output="reachBuffer",
                angle=0,
                column="BfWdth_Avg",
                scale=10)

    run_command("g.region",
                vector="reachBuffer",
                grow=500)

    run_command("r.clip",
                overwrite = True,
                input="JohnDayWShed@PERMANENT",
                output="DEM")

    run_command("r.colors",
                map="DEM",
                color="elevation")

    run_command("r.relief",
                overwrite = True,
                input="DEM",
                output="relief",
                altitude=30,
                azimuth=270,
                zscale=1,
                scale=1)

    run_command("r.shade",
                overwrite = True,
                shade="relief",
                color="DEM",
                output="demShade",
                brighten=0)

    run_command("r.slope.aspect",
                overwrite = True,
                elevation="DEM",
                slope="slope",
                format="degrees",
                precision="FCELL",
                zscale=1.0,
                min_slope=0.0)

    run_command("d.vect",
                map="reachBuffer",
                layer="1",
                display="shape",
                type="point,line,area,face",
                color="black",
                fill_color="none",
                width=2,
                width_scale=1,
                icon="basic/x",
                size=5,
                icon_area="legend/area",
                icon_line="legend/line",
                label_layer="1",
                label_color="red",
                label_bgcolor="none",
                label_bcolor="none",
                label_size=8,
                xref="left",
                yref="center")

    return 0

if __name__ == "__main__":
    options, flags = parser()
    atexit.register(cleanup)
    sys.exit(main(options, flags))
